# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Upload apk to app center"
  lane :upload_apk do
    owner_name = "IndoorAtlas"
    app_name = "GS-example-1"
    appcenter_api_token = ENV["APPCENTER_API_TOKEN"]
    versions_old = appcenter_fetch_version_number(
      api_token: appcenter_api_token,
      owner_name: owner_name,
      app_name: app_name
    )
    increment_version_code(
      app_project_dir: "app",
      version_code: versions_old["build_number"].to_i + 1
    )
    gradle(
      task: "clean assembleDebug",
      flags: "--stacktrace",
      properties: {
        "bintrayUser": "#{ENV["BINTRAY_USER"]}",
        "bintrayApiKey": "#{ENV["BINTRAY_API_KEY"]}",
        "googleMapsApiKey": "#{ENV["MAP_API_KEY"]}",
        "iagsApiKey": "#{ENV["SITCP_API_KEY"]}",
        "iagsApiSecret": "#{ENV["SITCP_SECRET"]}"
      }
    )
    appcenter_upload(
      api_token: appcenter_api_token,
      owner_name: owner_name,
      owner_type: "organization",
      app_name: app_name,
      file: "app/build/outputs/apk/debug/app-debug.apk"
    )
    versions = appcenter_fetch_version_number(
      api_token: appcenter_api_token,
      owner_name: owner_name,
      app_name: app_name
    )
    puts versions
    link = "https://appcenter.ms/orgs/IndoorAtlas/apps/GS-example-1/distribute/releases/#{versions['id']}"
    slack(
      message: "GroundSage Android example app #{versions['version']} (#{versions['build_number']}) uploaded to app center.",
      channel: "#alert-app-release",
      slack_url: "#{ENV["SLACK_URL"]}",
      attachment_properties: {
        image_url: "https://chart.googleapis.com/chart?cht=qr&chl=#{link}&chs=240x240",
        fields: [
          {
              title: "Download Link",
              value: link
          }
        ]
      },
      success: true
    )
  end
end
