# This is a basic workflow to help you get started with Actions

name: Build app

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - "app-release"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "apk"
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6" # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gem depns
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install
      - name: upload apk to app center
        run: bundle exec fastlane android upload_apk
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
          MAP_API_KEY: ${{ secrets.MAP_API_KEY }}
          IAGS_CUSTOM_ENDPOINT: ${{ secrets.IAGS_CUSTOM_ENDPOINT }}
          IA_CUSTOM_ENDPOINT: ${{ secrets.IA_CUSTOM_ENDPOINT }}
          SITCP_API_KEY: ${{ secrets.SITCP_API_KEY }}
          SITCP_SECRET: ${{ secrets.SITCP_SECRET }}
          APPCENTER_API_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}
